"""create notes table

Revision ID: 40e972cb04e1
Revises: 8512c037b333
Create Date: 2025-01-23 13:39:35.958720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40e972cb04e1'
down_revision: Union[str, None] = '8512c037b333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_session_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reading_session_id'], ['reading_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.alter_column('intervals', 'type',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('WORK', 'SHORT_BREAK', 'LONG_BREAK', name='intervaltype'),
               existing_nullable=True)
    op.alter_column('intervals', 'status',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='intervalstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intervals', 'status',
               existing_type=sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='intervalstatus'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.alter_column('intervals', 'type',
               existing_type=sa.Enum('WORK', 'SHORT_BREAK', 'LONG_BREAK', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
