"""add table of contents table

Revision ID: d443aa0e27da
Revises: 
Create Date: 2025-01-17 23:11:39.718279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'd443aa0e27da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if enum exists before creating it
    connection = op.get_bind()
    
    # Check if enum exists
    result = connection.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type 
                WHERE typname = 'bookprogressstatus'
            );
        """)
    )
    enum_exists = result.scalar()
    
    if not enum_exists:
        op.execute(text("CREATE TYPE bookprogressstatus AS ENUM ('IN_PROGRESS', 'COMPLETED')"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_of_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_of_contents_book_id'), 'table_of_contents', ['book_id'], unique=False)
    op.create_index(op.f('ix_table_of_contents_id'), 'table_of_contents', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('book_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('current_chapter', sa.Integer(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='bookprogressstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('book_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_progress_book_id'), 'book_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_progress_id'), 'book_progress', ['id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.String(), nullable=True),
    sa.Column('chapter_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='sessionstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('intervals_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_sessions_id'), 'reading_sessions', ['id'], unique=False)
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('WORK', 'SHORT_BREAK', 'LONG_BREAK', name='intervaltype'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='intervalstatus'), nullable=True),
    sa.Column('remaining_time', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervals_id'), 'intervals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervals_id'), table_name='intervals')
    op.drop_table('intervals')
    op.drop_index(op.f('ix_reading_sessions_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_book_progress_id'), table_name='book_progress')
    op.drop_index(op.f('ix_book_progress_book_id'), table_name='book_progress')
    op.drop_table('book_progress')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_table_of_contents_id'), table_name='table_of_contents')
    op.drop_index(op.f('ix_table_of_contents_book_id'), table_name='table_of_contents')
    op.drop_table('table_of_contents')
    # Only drop enum if it exists
    connection = op.get_bind()
    result = connection.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type 
                WHERE typname = 'bookprogressstatus'
            );
        """)
    )
    if result.scalar():
        op.execute(text('DROP TYPE bookprogressstatus'))
    # ### end Alembic commands ###
